### ISSUE TITLE
Segfault when GetLayer("nonexistant layer")

### ISSUE THREAD

**Issue by SilverWingedSeraph** [edoren/STP#11]
When using GetLayer, it would be quite useful to have some way to detect if the layer doesn't exist; currently, it returns some unallocated memory and causes a segfault.

**Comment by SilverWingedSeraph** [comment]
A note for people who might find this later: the address of the nonexistent MapLayer (i.e. `&map.GetLayer("nonexistant layer")`) will be `NULL`. Checking for that works fine, but is really quite a hack.

**Comment by edoren** [comment]
Right now I'm developing a version 1.0 to solve this kind of problems.
