### ISSUE TITLE
-DSFML_ROOT is overriden in extlibs

### ISSUE THREAD

**Issue by Nopey** [edoren/STP#28]
I'm using -DSFML_ROOT to point my dependancies (STP included) at my unusual SFML install location.
Adding cache to either SFML_DIR or SFML_ROOT allows the user (via cmake-gui, or with arguments) to override the default.

**Comment by Nopey** [comment]
Note that the CACHE symbol should probably also be added to PUGIXML and ZLIB.
Will be making a pr tomorrow afternoon, but heres a quick example of CACHE syntax:
`set(SFML_DIR "${DEPENDENCIES_DIR}/SFML" CACHE PATH "Path to SFML's Root. Should contain a folder named include, and lib.")`

**Comment by edoren** [comment]
Closed by #29
