### ISSUE TITLE
STP crashes the app with std::bad_alloc

### ISSUE THREAD

**Issue by hiramgeeks** [edoren/STP#5]
Hi,

I was writing some testing code with STP and SFML 2.1. Basically, I was just loading a TMX file as the tutorial teaches and I got this:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Process returned 134 (0x86)   execution time : 0.703 s
Press ENTER to continue.

After insisting for a few times, it was able to crash the entire OS (in this case Ubuntu Linux 14.04).

Any clues? Let me know if I can provide further info.

**Comment by edoren** [comment]
Closed for lack of information to debug the problem.
