### ISSUE TITLE
Cmake error - finding SFML directories

### ISSUE THREAD

**Issue by FDeityLink** [edoren/STP#9]
Whenever I run cmake on the cmakelists.txt, everything works fine until I get down to finding SFML. I set the SFML_INCLUDE_DIR variable to `<sfml root>/include` through the GUI, and always get the following error:
```
Could NOT find SFML (missing:  SFML_GRAPHICS_LIBRARY SFML_WINDOW_LIBRARY SFML_SYSTEM_LIBRARY)

-> SFML directory not found. Put the SFML's top-level path (containing "include" and "lib" directories) in the /extlibs folder.
```
Not sure how to add the path to the /extlibs folder, and I'm assuming that's where my problems are from

Sorry if I opened up an old repo.

thanks

**Comment by edoren** [comment]
I'm assuming you are using Windows, you should put the SFML include and lib directories in the extlibs/SFML folder.
